services:
  app:
    image: fscarmen/argo-x:okteto
    ports:
      - "80:3000"
    environment:
      - NEZHA_SERVER=$NEZHA_SERVER
      - NEZHA_PORT=$NEZHA_PORT
      - NEZHA_KEY=$NEZHA_KEY
      - NEZHA_TLS=$NEZHA_TLS
